# Generated by Django 4.2.2 on 2023-06-20 20:30

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="state",
            field=django_fsm.FSMField(default="draft", max_length=50),
        ),
    ]
